### ISSUE TITLE
Store messages offline .. sending is a flag to determine whether it has been delivered or not

### ISSUE THREAD

**Issue by operatorjen** [mozilla/chatspaces#12]
including @sole in this convo .. localForage maybe?

**Comment by fwenzel** [comment]
yes

**Comment by operatorjen** [comment]
something like this for indexeddb data layout

```
chat:userHash: [
    chatObj,
    chatObj
]
```

**Comment by operatorjen** [comment]
https://github.com/mozilla/chatspaces/commit/c38af46438e66f8c6e6c8c95b035be5ee0eaf8aa
