### ISSUE TITLE
Update gumHelper to latest

### ISSUE THREAD

**Issue by operatorjen** [mozilla/chatspaces#14]
Note that I sent in custom 4:3 height and width in https://github.com/mozilla/chatspaces/blob/master/public/javascripts/controllers.js#L181 to shave off some file size :)

**Comment by operatorjen** [comment]
@sole sooo i just updated to prod with the newest changes and am still getting that DOM Exception error :(

**Comment by sole** [comment]
I think that is related to not switching off the camera and launching another one. If I replied to a thread or created a new one with the camera off initially, it works. Once you try to do something else afterwards it chokes. I think it's a different bug.

**Comment by sole** [comment]
This is fixed already.
