### ISSUE TITLE
Animated_GIF throws Exception sometimes 

### ISSUE THREAD

**Issue by operatorjen** [mozilla/chatspaces#20]
I'll add more details tomorrow about the error in here.

**Comment by operatorjen** [comment]
Dom Exception Error:

Index or size is negative or greater than the allowed amount

on http://spaces.meatspac.es/javascripts/vendor/animated-gif/src/Animated_GIF.js line 208

result: 2152923137

**Comment by operatorjen** [comment]
It doesn't seem to like angular. or vice versa. not sure why though.

**Comment by operatorjen** [comment]
fixed https://github.com/mozilla/chatspaces/commit/1b868076a986d874eac095497f8141747412396b

**Comment by sole** [comment]
hey Jen. I'm catching up on emails, is this the fix? https://github.com/sole/Animated_GIF/pull/4

**Comment by operatorjen** [comment]
@sole yep!

**Comment by sole** [comment]
thanks, I'll update it--will probably work on this today.
