### ISSUE TITLE
Probably does need a reply/reply all in the user message feed

### ISSUE THREAD

**Issue by operatorjen** [mozilla/chatspaces#24]

**Comment by fwenzel** [comment]
yes.

**Comment by operatorjen** [comment]
Can only be 'reply' not 'reply all' mainly because of the complexity where:
1. Person sends to recipients, and you may or may not be friends w/ the recipients.
2. You can't be sending messages to random recipients who aren't your friends
3. Sending messages to half the recipients that are your friends while not the others is weird I think

Thoughts?

**Comment by benitogf** [comment]
Hi IMHHO, the reply message should appear only with the friends that you have a message thread open, also a new message option should appear on the select friend, in case that you dont have a chat history, would love to help on this, still getting into your mvc edna :)

**Comment by operatorjen** [comment]
This is going to only have one reply and it will reply to all. Even people you don't follow. As per discussion with Maureen.

**Comment by operatorjen** [comment]
Solved in https://www.dropbox.com/s/72j7pye9x98nqux/2013-11-19%2014.00.33.jpg

**Comment by skiant** [comment]
:+1:
