### ISSUE TITLE
contacts not persisting after logout

### ISSUE THREAD

**Issue by kra** [mozilla/chatspaces#26]
As user karl, add contact with search at /friends, contact added, log out, log in, no contacts visible at /friends.  Expected contact to still be there after login.

**Comment by benitogf** [comment]
I found this behavior too, but its a bug of the get data from api (I think), after a few reloads I got the friends back

**Comment by operatorjen** [comment]
https://github.com/mozilla/chatspaces/commit/d7228a41a563eb19992bf9964e08224f5638d78d
