### ISSUE TITLE
Create a design brief for chatspaces

### ISSUE THREAD

**Issue by mhanratty** [mozilla/chatspaces#27]
I want to get more clarity on what chatspaces is all about so I can design an experience that really matches the purpose and personality of the product. I started a design brief for that we can all collaborate on. I started filling in some information but please edit and comment like crazy. 

https://docs.google.com/a/mozilla.com/document/d/1gAjrEGs9Vbgphab_ZkyK_Z32ClqW5hLcxCOWqyv4xIE/edit

**Comment by operatorjen** [comment]
@mhanratty updated with some notes! Should we have a meeting to go through this asap? // @sole

**Comment by sole** [comment]
gonna go through this doc now!! give me an hour or so :D
