### ISSUE TITLE
Make GIF prompt jump to a new view where the GIF takes up the screen

### ISSUE THREAD

**Issue by operatorjen** [mozilla/chatspaces#31]
@b3n0n

In the third screen, you see that clicking on the GIFCam button should move to a view that is only the video stream and a button to record. 
1. Make sure the video is a fixed 4:3 ratio... 320 x 240 in this case  - and centered :)
2. Once the record button is clicked (don't worry about a progress bar or anything), it should do the 2 second record and pass the data to the form as it does now.
3. The gif should display beside the message as a preview in `<img>`

**Comment by operatorjen** [comment]
@b3n0n can you hold off on this change until tomorrow (also do a git pull on this master branch) - I am switching the database with a new one and a new node module so the data structure will be different.

**Comment by benitogf** [comment]
ok, I will wait for the jamon no problem :)

**Comment by operatorjen** [comment]
fixed. i can't find the merge commit so just closing.
