### ISSUE TITLE
Replying to a thread [ux]

### ISSUE THREAD

**Issue by mhanratty** [mozilla/chatspaces#36]
Here's a flow for a quick reply to a thread.

![2013-11-22 13 55 51](https://f.cloud.github.com/assets/4432402/1604614/0df69cf0-53c2-11e3-8886-8ca5fa86cb57.jpg)
1. Meatbro is on "Threads" screen and selects a thread by clicking on it.
2. Meatbro views entire thread. At the top of the thread is his last gif, a text area to input some pithy text and a "Send" link. If meatbro wants a new gif he can click the icon/link to open up video app. At the bottom in a small toolbar Meatbro can see all his friends in the chat. 
3. Meatbro is happy with his existing gif so he writes a quick message and clicks "Send."
4. Meatbro's message is added at the top of the list. The reply field is cleared and ready for more of his amazing witticisms.

**Comment by operatorjen** [comment]
functionality fixed here https://github.com/mozilla/chatspaces/commit/52b94ecee2f790cfa174a86ff073feb45e3cd7b6
