### ISSUE TITLE
Experiment with reducing GIF size

### ISSUE THREAD

**Issue by sole** [mozilla/chatspaces#44]
currently they're ~ 100kb, make them smaller!

**Comment by operatorjen** [comment]
I think we can do this w/ the latest changes.. I'll just update bower w/ your new Animated_GIF stuff

**Comment by sole** [comment]
They were small already weren't them? we're talking a different thing, I think

**Comment by operatorjen** [comment]
I just ended up reducing the dimension.. didn't need to customize in this case.. and dropped it to about 56 kb.

**Comment by operatorjen** [comment]
https://github.com/mozilla/chatspaces/commit/683acbca2be52e82b4ec065b62c630442da6238e
