### ISSUE TITLE
Don't include profile pic of the user on the thread. Include the profile pic of the person(s) I sent the message to.

### ISSUE THREAD

**Issue by mhanratty** [mozilla/chatspaces#46]
I don't need to see my own photo on the thread. I do want to see the profile pic of the person I sent the message to. So for this thread I shouldn't see my pic but ednapiranha's profile pic.

![screenshot 2013-12-08 19 29 31](https://f.cloud.github.com/assets/4432402/1702131/5b626f42-6082-11e3-8120-f796b20b5caa.png)

**Comment by operatorjen** [comment]
https://github.com/mozilla/chatspaces/commit/8d7f365fc06560698aac21d48bd3d6f0641353c2
