### ISSUE TITLE
On an existing thread I should be able to send a message without creating a new gif

### ISSUE THREAD

**Issue by mhanratty** [mozilla/chatspaces#47]
On a thread where I have already uploaded an image, it should let me send another message without attaching a new gif. If I don't attach a new gif or image it should use the gif or image I last uploaded to the thread.
![screenshot 2013-12-08 19 36 13](https://f.cloud.github.com/assets/4432402/1702141/36b39c7e-6083-11e3-94b7-3c002287a743.png)

**Comment by operatorjen** [comment]
https://github.com/mozilla/chatspaces/commit/b694333c547dc53f1e626496c12094d3f2ecca0c
