### ISSUE TITLE
On a pre-exiting thread I should not have to specify a recipient. It should send the message to the recipient(s) already attached to the thread.

### ISSUE THREAD

**Issue by mhanratty** [mozilla/chatspaces#48]
Since I sent the first message on the thread to ednapiranha, it should go ahead and send my next message in the thread to her--I shouldn't need to specify her as the recipient.
![screenshot 2013-12-08 19 36 13](https://f.cloud.github.com/assets/4432402/1702156/fcc7450a-6083-11e3-90f4-e6ccb0b6176c.png)

**Comment by operatorjen** [comment]
Was it because you didn't include a gif on the reply? If not it throws that generic error message (not necessarily b/c the recipient isn't included)

**Comment by operatorjen** [comment]
I think this is fixed now!
