### ISSUE TITLE
Feature request: Groups?

### ISSUE THREAD

**Issue by mhanratty** [mozilla/chatspaces#49]
Should users be able to make groups? I heard that's the way a lot of folks use Whatsapp. They create groups and receive notifications when someone posts to the group. According to a user on Quora group conversations "are an absolute necessity when talking about hotties" (http://www.quora.com/WhatsApp-Messenger/Why-is-WhatsApp-Messenger-so-popular-Is-it-fun).

I think chatspaces should support conversations about hotties.

**Comment by benitogf** [comment]
the threads could be the groups, one unique thread for a group of users? hotties threads included, thats the way that whatsapp do it actually I think

**Comment by operatorjen** [comment]
I think users shouldn't make groups (as discussed yesterday). The current conversation should be the group or else it adds complications.
