### ISSUE TITLE
[UX] Adding a new contact

### ISSUE THREAD

**Issue by mhanratty** [mozilla/chatspaces#50]
Here is a flow for adding a contact to chatspaces. I divided the screens so that the search on the "Friends" screen only searches through your existing contacts. If you want to add a new contact you do that through another screen. The design on the contacts screen is similar to what is being used on the FFOS Contacts app (http://mozorg.cdn.mozilla.net/media/img/l10n/en-US/firefox/os/have-it-all/contacts.jpg?2013-09). 

![2013-12-09 16 21 38](https://f.cloud.github.com/assets/4432402/1710482/113a8cfa-6132-11e3-9053-170b242bccd6.jpg)
![2013-12-09 16 21 44](https://f.cloud.github.com/assets/4432402/1710483/113b104e-6132-11e3-864b-998217791593.jpg)
1. User clicks "+" icon to add contact
2. User sees screen to add friend. User can search existing chatspace users. User enters chatspace user name.
3. User sees result. User selects the username to add
4. Show name selected.
5. User sees feedback that the contact has been added. User can enter additional usernames and add more folks or click "Done"
6. User returns to "Friends" screen and sees that contact was added.

The search by username UI comes from the curation tool. Thought it would be helpful here as you can add multiple people at one time. 
https://marketplace-dev.allizom.org/curation/
![screenshot 2013-12-09 16 28 04](https://f.cloud.github.com/assets/4432402/1710478/01b5d0aa-6132-11e3-834f-4862c467cf49.png)

**Comment by operatorjen** [comment]
completed
