### ISSUE TITLE
Layout of new message form in terms of video focus, message, recipients, error message

### ISSUE THREAD

**Issue by operatorjen** [mozilla/chatspaces#6]

**Comment by operatorjen** [comment]
The way a lot of the existing apps do it (Snapchat, FB Poke, etc) is that they show two separate screens: one for selecting the users, the second for showing the message input area. That might actually work since mobile is such a small area.

**Comment by operatorjen** [comment]
Which leads me to think that maybe the new message screen shouldn't be a dropdown overlay but an actual separate page...

**Comment by mhanratty** [comment]
![2013-11-17 20 24 57](https://f.cloud.github.com/assets/4432402/1560510/160f6d2e-500a-11e3-97ae-8c312201618e.jpg)
![2013-11-17 20 25 09](https://f.cloud.github.com/assets/4432402/1560511/26ef2508-500a-11e3-8c1f-aafc29afbe03.jpg)

Here are some sketches of how I think the new message flow would work on mobile. I'm separating out the composing message and selecting friends screens--I think it's better to let folks really focus on creating a cool, funny message without the clutter of adding friends.
1. Person chooses new message
2. Person sees screen to compose message. Sees their last gif. 
3. Person chooses to upload a new gif opening up camera app. 
4. Person returns to compose message screen, types message. Selects Next
5. Person selects friends to send message to. Selects Send.
6. Person taken to message screen and sees new message posted.
