### ISSUE TITLE
Pressing enter after writing message in thread sends the message without camera prompt

### ISSUE THREAD

**Issue by sole** [mozilla/chatspaces#67]
Not sure if this is expected behaviour or a bug!

**Comment by operatorjen** [comment]
oh yeah.. expected ig uess.. b/c you have the 'last picture' saved from before.. but i guess i can always prompt it

**Comment by operatorjen** [comment]
https://github.com/mozilla/chatspaces/commit/a5aa7ae0a01e9373bc3c79036f5bcb4a6db5c1c3
