### ISSUE TITLE
Duplicated string but not quite duplicated

### ISSUE THREAD

**Issue by sole** [mozilla/chatspaces#73]
Seems like there are two pretty similar strings in the locales:

LOCAL_CACHE_RESET: Local cache reset
https://github.com/mozilla/chatspaces/blob/e284db576cf44efd975ed64d25241faccc8d198d/public/locales/en.json#L11

and

RESET_LOCAL_CACHE: "Reset local cache"
https://github.com/mozilla/chatspaces/blob/e284db576cf44efd975ed64d25241faccc8d198d/public/locales/en.json#L33

Is this right? :question:

**Comment by operatorjen** [comment]
Yep.. one is the button and one is for the message to let the user know that it was reset.
