### ISSUE TITLE
User creation workflow: Done and next button together

### ISSUE THREAD

**Issue by fwenzel** [mozilla/chatspaces#77]
I failed to take a screenshot :-/ but on the page where you take your avatar pic, it ends up showing you "done" and "next" next to each other. It's not clear what, if any, difference there is between the buttons.

**Comment by operatorjen** [comment]
hmm wording.. @mhanratty ?

**Comment by operatorjen** [comment]
oh wait.. i see this.. it's a bug..

**Comment by operatorjen** [comment]
https://github.com/mozilla/chatspaces/commit/24b5edccf9de79c0623e936dc519b36c2d966443
