### ISSUE TITLE
camera stays on after sending message

### ISSUE THREAD

**Issue by jlongster** [mozilla/chatspaces#9]
After sending a message with a gif, and moving away to other parts of the app, the green light on my camera stayed on. I want privacy!!

**Comment by fwenzel** [comment]
Good call. Also, battery life. Only use the camera for as long as you need it.

**Comment by operatorjen** [comment]
oops good point! will take a look!

**Comment by fwenzel** [comment]
I think that's this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=937645

**Comment by sole** [comment]
no, I think it's just that gumhelper.stop might not being called? I can have a look after cascadia
